---
title: "ACST886 Assignment2 Q3 5.9"
author: "Chang Liu"
date: "04/09/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message=FALSE)
```

## 5.9
### Processing data
```{r}
x<-c(47:67)
IExpose2risk<-c(166,187,218,243,276,302,347,390,430,494,558,628,701,813,917,1040,1182,1299,1432,1596,1752)
d_x<-c(2,2,4,6,2,4,7,3,9,9,8,11,14,18,18,24,30,43,41,54,64)
qs_x<-c(0.00505,0.0057,0.00644,0.00728,0.00826,0.0093,0.01051,0.01184,0.01331,0.01492,0.01668,0.01859,0.02065,0.02287,0.02525,0.02778,0.03049,0.03339,0.03648,0.03978,0.04332)
q_x<-d_x/IExpose2risk
```

### obtain function to estimate parameterusing weighted least squares
```{r}
f<-function(p){sum(IExpose2risk*(q_x-p[1]-p[2]*qs_x)^2)}
```

### obtain initial values by regression
```{r}
junk<-lm(log(q_x)~x)
iv<-exp(as.numeric(junk$coefficients))
```

### using nlm function to get a,b using initial values.
```{r}
para<-nlm(f,iv)
a=para$estimate[1]
b=para$estimate[2]
a
b
```

### obtain graduate estimates using a and b
```{r}
q_grad<-a+b*qs_x
q_grad
```